name: MaskRR
channels:
  - pytorch
  - astra-toolbox
dependencies:
  - python=3.9.13
  - numpy=1.23.3
  - pandas=1.5.1
  - h5py=3.7.0
  - scikit-image=0.19.3
  - pytorch::pytorch=1.12.1
  - pytorch::torchvision=0.13.1
  - torchmetrics=1.1.2
  - astra-toolbox::astra-toolbox=2.1.2
  - pip
  - pip:
    - dival==0.6.1
    - opencv-python
    - fastmri==0.3.0
    - timm=0.9.8
